#!/bin/bash

echo "Running Sanity Typegen script..."

SCHEMA_PATH=src/lib/sanity/types/schema.json

npx sanity schema extract --path $SCHEMA_PATH --enforce-required-fields

npx sanity typegen generate
