name: Build and Deploy to S3

on:
    push:
        branches:
            - master
    repository_dispatch:
        types:
            - trigger_deployment

jobs:
    build:
        name: Build project
        runs-on: ubuntu-latest
        env:
            PUBLIC_SANITY_PROJECT_ID: ${{vars.SANITY_PROJECT_ID}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.9
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: astro-dist
                  path: dist/
                  retention-days: 1
                  overwrite: true

    deploy:
        name: Deploy to S3
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: astro-dist
                  path: dist

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: ${{vars.AWS_REGION}}
                  role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT}}:role/${{vars.AWS_ROLE}}

            - name: Sync dist to S3
              run: |
                  aws s3 sync ./dist s3://${{vars.AWS_S3_BUCKET}} --delete

            - name: Invalidate CloudFront cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{vars.AWS_CLOUDFRONT_ID}} --paths "/*"
